using System.ComponentModel;

namespace JD_XI_Editor.Models.Enums.Common
{
    internal enum NotePitch : byte
    {
        //Octave -1
        [Description("C-1")] CMinus1 = 0x00,
        [Description("C#-1")] CSharpMinus1 = 0x01,
        [Description("D-1")] DMinus1,
        [Description("D#-1")] DSharpMinus1,
        [Description("E-1")] EMinus1,
        [Description("F-1")] FMinus1,
        [Description("F#-1")] FSharpMinus1,
        [Description("G-1")] GMinus1,
        [Description("G#-1")] GSharpMinus1,
        [Description("A-1")] AMinus1,
        [Description("A#-1")] ASharpMinus1,
        [Description("B-1")] BMinus1,

        //Octave 0
        [Description("C0")] C0,
        [Description("C#0")] CSharp0,
        [Description("D0")] D0,
        [Description("D#0")] DSharp0,
        [Description("E0")] E0,
        [Description("F0")] F0,
        [Description("F#0")] FSharp0,
        [Description("G0")] G0,
        [Description("G#0")] GSharp0,
        [Description("A0")] A0,
        [Description("A#0")] ASharp0,
        [Description("B0")] B0,

        //Octave 1
        [Description("C1")] C1,
        [Description("C#1")] CSharp1,
        [Description("D1")] D1,
        [Description("D#1")] DSharp1,
        [Description("E1")] E1,
        [Description("F1")] F1,
        [Description("F#1")] FSharp1,
        [Description("G1")] G1,
        [Description("G#1")] GSharp1,
        [Description("A1")] A1,
        [Description("A#1")] ASharp1,
        [Description("B1")] B1,

        //Octave 2
        [Description("C2")] C2,
        [Description("C#2")] CSharp2,
        [Description("D2")] D2,
        [Description("D#2")] DSharp2,
        [Description("E2")] E2,
        [Description("F2")] F2,
        [Description("F#2")] FSharp2,
        [Description("G2")] G2,
        [Description("G#2")] GSharp2,
        [Description("A2")] A2,
        [Description("A#2")] ASharp2,
        [Description("B2")] B2,

        //Octave 3
        [Description("C3")] C3,
        [Description("C#3")] CSharp3,
        [Description("D3")] D3,
        [Description("D#3")] DSharp3,
        [Description("E3")] E3,
        [Description("F3")] F3,
        [Description("F#3")] FSharp3,
        [Description("G3")] G3,
        [Description("G#3")] GSharp3,
        [Description("A3")] A3,
        [Description("A#3")] ASharp3,
        [Description("B3")] B3,

        //Octave 4
        [Description("C4")] C4,
        [Description("C#4")] CSharp4,
        [Description("D4")] D4,
        [Description("D#4")] DSharp4,
        [Description("E4")] E4,
        [Description("F4")] F4,
        [Description("F#4")] FSharp4,
        [Description("G4")] G4,
        [Description("G#4")] GSharp4,
        [Description("A4")] A4,
        [Description("A#4")] ASharp4,
        [Description("B4")] B4,

        //Octave 5
        [Description("C5")] C5,
        [Description("C#5")] CSharp5,
        [Description("D5")] D5,
        [Description("D#5")] DSharp5,
        [Description("E5")] E5,
        [Description("F5")] F5,
        [Description("F#5")] FSharp5,
        [Description("G5")] G5,
        [Description("G#5")] GSharp5,
        [Description("A5")] A5,
        [Description("A#5")] ASharp5,
        [Description("B5")] B5,

        //Octave 6
        [Description("C6")] C6,
        [Description("C#6")] CSharp6,
        [Description("D6")] D6,
        [Description("D#6")] DSharp6,
        [Description("E6")] E6,
        [Description("F6")] F6,
        [Description("F#6")] FSharp6,
        [Description("G6")] G6,
        [Description("G#6")] GSharp6,
        [Description("A6")] A6,
        [Description("A#6")] ASharp6,
        [Description("B6")] B6,

        //Octave 7
        [Description("C7")] C7,
        [Description("C#7")] CSharp7,
        [Description("D7")] D7,
        [Description("D#7")] DSharp7,
        [Description("E7")] E7,
        [Description("F7")] F7,
        [Description("F#7")] FSharp7,
        [Description("G7")] G7,
        [Description("G#7")] GSharp7,
        [Description("A7")] A7,
        [Description("A#7")] ASharp7,
        [Description("B7")] B7,

        //Octave 8
        [Description("C8")] C8,
        [Description("C#8")] CSharp8,
        [Description("D8")] D8,
        [Description("D#8")] DSharp8,
        [Description("E8")] E8,
        [Description("F8")] F8,
        [Description("F#8")] FSharp8,
        [Description("G8")] G8,
        [Description("G#8")] GSharp8,
        [Description("A8")] A8,
        [Description("A#8")] ASharp8,
        [Description("B8")] B8,

        //Octave 9
        [Description("C9")] C9,
        [Description("C#9")] CSharp9,
        [Description("D9")] D9,
        [Description("D#9")] DSharp9,
        [Description("E9")] E9,
        [Description("F9")] F9,
        [Description("F#9")] FSharp9,
        [Description("G9")] G9
    }
}